services:
    application_factory:
        class: Helstern\Nomsky\Application\CliApplicationFactory
        arguments: ["@analyze_ebnf_command"]
    analyze_ebnf_command:
        class: Helstern\Nomsky\Analyze\EbnfCommand
        arguments:
            - "@console_options"
    console_options:
        class: Helstern\Nomsky\Analyze\ConsoleOptions
